version: '3.8'
services:

    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            args:
                DOCKER_PHP_VERSION: ${DOCKER_PHP_VERSION}
        container_name: ${APP_NAME}_app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: ${APP_NAME}
            SERVICE_TAGS: dev
        working_dir: /var/www
        depends_on:
            - db
            - redis
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: ${APP_NAME}_nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8080:${DOCKER_NGINX_PORT}"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    db:
        image: ${DB_CONNECTION}:${DOCKER_DB_VERSION}
        container_name: ${APP_NAME}_db
        restart: unless-stopped
        tty: true
        ports:
            - "${DB_PORT}:${DB_PORT}"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - db-data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf:ro
        networks:
            - app-network

    redis:
        image: redis:${DOCKER_REDIS_VERSION}
        container_name: ${APP_NAME}_redis
        restart: always
        ports:
            - "${REDIS_PORT}:${REDIS_PORT}"
        command: redis-server --save 60 1 --requirepass ${REDIS_PASSWORD} --loglevel debug
        volumes:
            - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - redis-data:/data

    phpmyadmin:
        image: phpmyadmin
        container_name: ${APP_NAME}_phpmyadmin
        restart: always
        links:
            - db
        ports:
            - ${DOCKER_MY_ADMIN_PORT}:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_PORT: ${DB_PORT}
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        networks:
            - app-network

networks:
    app-network:
        name: ${APP_NAME}_network
        driver: bridge

volumes:
    db-data:
        driver: local
    redis-data:
        driver: local
